FROM ruby:3.1.2-bullseye

# Install dependencies
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs iputils-ping imagemagick

# Set an environment variable where the Rails app is installed to inside of Docker image:
ENV RAILS_ROOT /var/www/test_app
RUN mkdir -p $RAILS_ROOT

# Set working directory, where the commands will be ran:
WORKDIR $RAILS_ROOT

# Setting env up
ENV RAILS_ENV='production'
ENV RACK_ENV='production'

# Adding gems
COPY Gemfile Gemfile
COPY Gemfile.lock Gemfile.lock
COPY config/master.key config/master.key
RUN bundle install --jobs 20 --retry 5 --without development test

# Adding project files
COPY . .

RUN bundle exec rake assets:precompile

ADD app/javascript/custom public/assets

EXPOSE 3000

COPY ./lib/docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["bundle", "exec", "puma", "-C", "config/puma.rb"]