apiVersion: batch/v1
kind: Job
metadata:
  name: busca-cursos-startup-migrate
  labels:
    app.kubernetes.io/name: busca-cursos-startup-migrate
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: busca-cursos-startup-migrate
    spec:
      containers:
      - command:
        - rails
        - db:migrate
        envFrom:
        - configMapRef:
            name: busca-cursos-startup
        image: docker.io/geshan/busca-cursos-startup:latest
        imagePullPolicy: IfNotPresent
        name: main
      restartPolicy: Never