apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: busca-cursos-startup
    process: web
  name: busca-cursos-startup-web
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: busca-cursos-startup
      process: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: busca-cursos-startup
        process: web
    spec:
      containers:
      - env:
        - name: PORT
          value: "3000"
        envFrom:
        - configMapRef:
            name: busca-cursos-startup
        image: docker.io/geshan/busca-cursos-startup:latest
        imagePullPolicy: IfNotPresent
        name: busca-cursos-startup-web
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 2
        resources:
          limits:
            cpu: "200m"
            memory: "128Mi"
          requests:
            cpu: "150m"
            memory: "128Mi"
      restartPolicy: Always