version: "3.9"
services:
  # db:
  #   image: postgres
  #   volumes:
  #     - ./tmp/db:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_PASSWORD: password

  web:
    # Cambiar puerto a 8080 para correr local, así no topa con vue
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 8080 -b '0.0.0.0'"
    volumes:
      - .:/ruterocl
    ports:
      - "8080:8080"
    # depends_on:
    #   - db
    env_file:
      - ./.env