version: "3"
services:
  # db:
  #   image: postgres
  #   volumes:
  #     - ./tmp/db:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_PASSWORD: password

  web-first:
    # Cambiar puerto a 8080 para correr local, así no topa con vue
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 8080 -b '0.0.0.0'"
    volumes:
      - .:/busca-cursos-startup
    image: marianatr/busca-cursos-startup-web-first-1
    ports:
      - "8080:8080"
    # depends_on:
    #   - db
    # env_file:
    #   - ./.env	

  nginx:
     build:
       context: .
       dockerfile: ./nginx.Dockerfile
     ports:
       - "83:83"
     depends_on:
       - web-first
   